//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffDepartment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StDbEntities : DbContext
    {
        public StDbEntities()
            : base("name=StDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Educations> Educations { get; set; }
        public virtual DbSet<Passports> Passports { get; set; }
        public virtual DbSet<WorkBooks> WorkBooks { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<WorkPlaces> WorkPlaces { get; set; }
    }
}
