//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passports
    {
        public int Id { get; set; }
        public string PassportType { get; set; }
        public string Series { get; set; }
        public int Number { get; set; }
        public string Gave { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public int WorkerID { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
