//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlaces
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int WokrBookID { get; set; }
    
        public virtual WorkBooks WorkBooks { get; set; }
    }
}
